name: Sudoku app CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  install:
    name: 'install'
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          pwd
          ls
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install NPM Dependencies
        run: npm i

  test:
    name: 'test'
    needs: install
    runs-on: ubuntu-latest
    steps:
      - run: yarn test

  build:
    name: 'build'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: yarn build

  deploy:
    name: 'deploy'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist
      - name: Deploy to surge
        run: |
          npm i -g surge
          surge --project ./dist --domain sudokuapp.surge.sh
          echo "DEPLOY DONE HURRAY"
